### ISSUE TITLE
mqtt formatting

### ISSUE THREAD

**Issue by germil** [apreb/eNode#2]
Please give us more information about mqtt formating, for easier integration with Home assistant.
What should broker call look like, and what does enode message look like?
Thank you.

**Comment by apreb** [comment]
eNode has the following MQTT implementation:

[base] and [name] are configured on the web interface

For this example:

[base] = enode
[name] = aqs

eNode subscribes at `/enode/aqs/to`
eNode publishes  at `/enode/aqs/from`

since pubsub library has small message limits i had to divide energy from temperature:

`/enode/aqs/from/temperature`
`/enode/aqs/from/energy`

Example:
`enode/aqs/from/energy {"Ts":"1321890","Va":237.9,"Aa":0.00,"Pa":0}`
`enode/aqs/from/temperature {"Ts":"1321890","T0":35.25,"T1":16.00,"T2":27.13,"T3":54.56}`

`Ts` is the uptime



Boot and LastWill message:

persistent topic `client/aqs`

@boot: `client/aqs enode@192.168.xxx.xxx`
@disconnect: `client/aqs offline`

Commands:

`B` - reboot the eNode
`d` - toggle debug messages (persistent)
`r[1-99]` - sets the refresh rate in seconds
`r` - reverts the refresh rate to the original configured on the web page
`O` - checks the state of the relay "Oon" or "Ooff"
`O[0,1,2]` - Sets relay, 0-off, 1-on, 2-toggle

**Comment by germil** [comment]
Thank you,
in **mqttleens** i subscribe to: client/energija and 
i only get "online@192.168.2.212"
my configuration:
[base] = enode
[name] = enegija
on enode webpage i get those readings:
{"Ts":"6469","Va":"238.40","Aa":"0.10","Pa":"1","PFa":"0.04","Vb":"237.40","Ab":"0.10","Pb":"1","Vc":"237.70","Ac":"0.21","Pc":"3","T0":"20.81"}
What should i subscribe to enode, to get those readings back in message?

Thank you, i find enode perfect solution for my needs, just have to implement it to Home assistant.
Nice job!

**Comment by apreb** [comment]
subscribe to `enode/enegija/#` to see all messages.
subscribe to `enode/enegija/from/energy` to get energy readings
subscribe to `enode/enegija/from/temperature` to get DS18B20 readings

**Comment by germil** [comment]
Thank you, just solved the problem.
Im a total noob, but i find out that when i supscribe just #, i got all the readings to mqttlens.
Thank you for support, and keep going with such a good projects.
Hope, you understand what i ment.
Im bad english speaker.
Best regards, Milan
